### ISSUE TITLE
registrofiscal  is not a valid URI

### ISSUE THREAD

**Issue by heris16** [phpcfdi/cfdi-to-json#12]
![image](https://user-images.githubusercontent.com/16210500/174665139-a50225d5-5b8b-42c0-950c-7bb1bf5327c8.png)

**Comment by eclipxe13** [comment]
El CFDI tiene errores, te recomiendo que primero lo limpies con [`phpcfdi/cfdi-cleaner`](https://github.com/phpcfdi/cfdi-cleaner).

En específico, tu XML debería decir `xsi:schemaLocation` y no `xmlns:schemaLocation`

**Comment by eclipxe13** [comment]
Mira el issue #2
Se trata del mismo problema que tienes.
