### ISSUE TITLE
Error en Complemento RegistroFiscal

### ISSUE THREAD

**Issue by vnetmx** [phpcfdi/cfdi-to-json#2]
Hola, estoy teniendo éste error al procesar un CFDI
`
[2021-02-18 04:05:12] local.ERROR: DOMDocument::loadXML(): xmlns:schemaLocation: 'http://www.sat.gob.mx/registrofiscal http://www.sat.gob.mx/sitio_internet/cfd/cfdiregistrofiscal/cfdiregistrofiscal.xsd' is not a valid URI in Entity, line: 20 {"userId":1,"exception":"[object] (ErrorException(code: 0): DOMDocument::loadXML(): xmlns:schemaLocation: 'http://www.sat.gob.mx/registrofiscal http://www.sat.gob.mx/sitio_internet/cfd/cfdiregistrofiscal/cfdiregistrofiscal.xsd' is not a valid URI in Entity, line: 20 at  vendor/phpcfdi/cfdi-to-json/src/CfdiToDataNode.php:26)
[stacktrace]
`
Alguien sabe a que se deba?

**Comment by eclipxe13** [comment]
Sí. El CFDI que estás intentando leer contiene errores. Justo donde dice `xmlns:schemaLocation` debería decir `xsi:schemaLocation`.

¿Podrías hacer la prueba para ver si mi idea es correcta?

Otra pregunta, ¿el CFDI lo descargaste directamente del SAT?

**Comment by eclipxe13** [comment]
Te recomiendo usar el "limpiador" de CFDI de `eclipxe/cfdiutils`, la documentación está aquí:
https://cfdiutils.readthedocs.io/es/latest/leer/limpieza-cfdi/#objeto-cleaner

De esta forma tendrás algunas ventajas útiles:
- Corregir este problema conocido del `schemaLocation`
- Colapsar los `Comprobante\Complemento` en uno solo.

**Comment by vnetmx** [comment]
> Sí. El CFDI que estás intentando leer contiene errores. Justo donde dice `xmlns:schemaLocation` debería decir `xsi:schemaLocation`.
> 
> ¿Podrías hacer la prueba para ver si mi idea es correcta?
> 
> Otra pregunta, ¿el CFDI lo descargaste directamente del SAT?

Lo más curioso es que si lo baje directo del SAT, del descargar facturas, me aparecia valida y todo. Se supondría que ellos al timbrar (el PAC) hacen una pre-validación o no es así? Lo que hice como workaround, es antes de meterla al converter, fue hacer un preg_replace para eliminarlo.

**Comment by vnetmx** [comment]
> Te recomiendo usar el "limpiador" de CFDI de `eclipxe/cfdiutils`, la documentación está aquí:
> https://cfdiutils.readthedocs.io/es/latest/leer/limpieza-cfdi/#objeto-cleaner
> 
> De esta forma tendrás algunas ventajas útiles:
> 
> * Corregir este problema conocido del `schemaLocation`
> * Colapsar los `Comprobante\Complemento` en uno solo.

Va! Ese no lo tenía en el radar, me parece que si me será bastante útil.

**Comment by eclipxe13** [comment]
> Lo más curioso es que si lo baje directo del SAT, del descargar facturas, me aparecia valida y todo. Se supondría que ellos al timbrar (el PAC) hacen una pre-validación o no es así?

Sí, es curioso, pero seguramente este CFDI fue emitido por el propio SAT, este problema solo lo hemos encontrado en sus propias emisiones, como si ellos mismo no aplicaran las validaciones suficientes que sí exigen.

Si estarás trabajando con CFDI en PHP te recomiendo visitar la comunidad de phpcfdi en discord: https://discord.gg/aFGYXvX ahí habemos varias personas que nos enfrentamos a este tipo de problemas y nos compartimos este tipo de conocimientos.
